name: topgrade
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  get_storage:
#  sizer: ^2.0.15
  flutter_native_splash:
  intl_phone_field:
  otp_pin_field:
  salomon_bottom_bar: ^3.3.0
#  another_xlider: ^1.0.1+2
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.4
  expandable: ^5.0.1
  html: ^0.15.0
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  chewie: ^1.3.3
  video_player:
  file_picker: ^4.6.0
  flutter_svg: ^1.1.0
  flutterwave_standard: ^1.0.3
  firebase_core: ^1.18.0
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.18
  flutter_facebook_auth: ^4.3.4+2
  animated_text_kit: ^4.2.2
  # animated_text: ^1.0.2
  # flutter_login_facebook: ^1.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#ffa110"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill