// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6tlAU5CzcYGrCaVciJdLL5Ad-DR_WkAE',
    appId: '1:88432950243:web:bf1a7f7163373b182d3ed6',
    messagingSenderId: '88432950243',
    projectId: 'mytopgrade-361f5',
    authDomain: 'mytopgrade-361f5.firebaseapp.com',
    storageBucket: 'mytopgrade-361f5.appspot.com',
    measurementId: 'G-YBWP52DFW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5dJLjfPB2TtUbJlBNIRUkw87BWLYvzeA',
    appId: '1:88432950243:android:88210905a81023802d3ed6',
    messagingSenderId: '88432950243',
    projectId: 'mytopgrade-361f5',
    storageBucket: 'mytopgrade-361f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38Qqrh18EK_KbmtEv29JCdSZB0NXM8Lg',
    appId: '1:88432950243:ios:4c5cffa7c10433df2d3ed6',
    messagingSenderId: '88432950243',
    projectId: 'mytopgrade-361f5',
    storageBucket: 'mytopgrade-361f5.appspot.com',
    iosClientId: '88432950243-072qne2negb4auj6on184atlal59v593.apps.googleusercontent.com',
    iosBundleId: 'com.AZainapps.topgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38Qqrh18EK_KbmtEv29JCdSZB0NXM8Lg',
    appId: '1:88432950243:ios:ce4b3a5be517b3a52d3ed6',
    messagingSenderId: '88432950243',
    projectId: 'mytopgrade-361f5',
    storageBucket: 'mytopgrade-361f5.appspot.com',
    iosClientId: '88432950243-sf24s61vhq0hn6nub6j05sbmpqn9j4io.apps.googleusercontent.com',
    iosBundleId: 'com.aZainapps.tpgrade',
  );
}
